# Generated by Django 3.2.3 on 2022-09-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidSayim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parca_kodu', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Parça Kodu')),
                ('saha_kodu', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Saha Kodu')),
                ('saha_no', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Saha No')),
                ('department', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Department')),
                ('parca_tanimi', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Parça Tanımı')),
                ('sirket', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Sirket')),
                ('saha_tipi', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Saha Tipi')),
                ('parca_kodu_tipi', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Parça Kodu Tipi')),
                ('il', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='İl')),
                ('organizasyon', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Organizasyon')),
                ('eldeki_miktar', models.IntegerField(verbose_name='Eldeki Miktar')),
                ('kalem_dogruluk_orani', models.IntegerField(verbose_name='Kalem Dogruluk Orani')),
                ('nihai_sayim', models.IntegerField(verbose_name='Nihai Sayim')),
                ('sayim_baslangic_tarihi', models.DateField(blank=True, null=True, verbose_name='Sayim Baslangiç Tarihi')),
                ('sayim_bitis_tarihi', models.DateField(blank=True, null=True, verbose_name='Sayim Bitis Tarihi')),
                ('sayim_dogrulugu', models.IntegerField(verbose_name='Sayim Dogrulugu')),
                ('sayim_kullanici_tipi', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Sayim Kullanici Tipi')),
                ('sayim_kullanicisi', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Sayim Kullanicisi')),
                ('sayim_no', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Sayim No')),
            ],
        ),
    ]
