# Generated by Django 3.2.3 on 2022-09-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcakodlari', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcakodu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ekipman_tipi', models.CharField(default='', max_length=10, verbose_name='Tip')),
                ('olcum_birimi', models.CharField(default='', max_length=10, verbose_name='Birim')),
                ('parca_kodu', models.CharField(default='', max_length=50, verbose_name='Ekipman Parça Kodu')),
                ('parca_tanimi', models.CharField(default='', max_length=250, verbose_name='Parça Tanımı')),
                ('grup_tanimi', models.CharField(default='', max_length=250, verbose_name='Grup Tanımı')),
                ('ekip_tanimi', models.CharField(default='', max_length=250, verbose_name='Ekip Tanımı')),
                ('ekip_aciklama', models.CharField(default='', max_length=250, verbose_name='Ekip Açıklama')),
                ('muadil', models.CharField(default='', max_length=500, verbose_name='Muadil')),
            ],
            options={
                'verbose_name': 'Parça Kodu',
                'verbose_name_plural': 'Parça Kodu Listesi',
            },
        ),
        migrations.DeleteModel(
            name='ParcaKodlari',
        ),
    ]
