# Generated by Django 3.2.3 on 2022-09-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvanaterSayim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parca_kodu_tipi', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Parça Kodu Tipi')),
                ('islem_miktari', models.IntegerField(verbose_name='Islem Miktari')),
                ('islem_no', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Islem No')),
                ('islem_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Islem Tarihi')),
                ('islem_tipi', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Islem Tipi')),
                ('source_code', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Source Code')),
                ('parca_kodu', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Parça Kodu')),
                ('saha_kodu', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Saha Kodu')),
                ('saha_no', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Saha No')),
                ('parca_tanimi', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Parça Tanımı')),
                ('sirket', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Sirket')),
                ('seri_no', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Seri No')),
                ('kullanici_adi', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Kullanici Adi')),
                ('olcum_birimi', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Olcum Birimi')),
                ('birim_maliyet', models.IntegerField(verbose_name='Birim Maliyet')),
                ('form_no', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Form No')),
                ('hedef_departman', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Hedef Departman')),
                ('ıslem_miktari', models.IntegerField(verbose_name='Islem Miktari')),
                ('ıslem_no', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Islem No')),
                ('ıslem_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Islem Tarihi')),
                ('ıslem_tipi', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Islem Tipi')),
                ('kalem_kategori', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Kalem Kategori')),
                ('kaynak_departman', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Kaynak Departman')),
                ('kaynak_organizasyon_kodu', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Kaynak Organizasyon Kodu')),
                ('kaynak_stok_adresi', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Kaynak Stok Adresi')),
                ('kaynak_stok_yeri', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Kaynak Stok Yeri')),
                ('kaynak_surec', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Kaynak Surec')),
                ('referans', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Referans')),
                ('transfer_organizasyon_kodu', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Transfer Organizasyon Kodu')),
                ('transfer_stok_adresi', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Transfer Stok Adresi')),
                ('transfer_stok_yeri', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Transfer Stok Yeri')),
                ('ıs_emri', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Is Emri')),
                ('onent_kullanici', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='ONENT Kullanici')),
            ],
        ),
        migrations.AddField(
            model_name='envanter',
            name='ana_yer_tipi',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Ana Yer Tipi'),
        ),
        migrations.AddField(
            model_name='envanter',
            name='department',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='envanter',
            name='ekipman_no',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Ekipman No'),
        ),
        migrations.AddField(
            model_name='envanter',
            name='kts_saha_no',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='KTS Saha No'),
        ),
        migrations.AddField(
            model_name='envanter',
            name='organizasyon',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Organizasyon'),
        ),
        migrations.AddField(
            model_name='envanter',
            name='parca_kodu',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Parça Kodu'),
        ),
        migrations.AddField(
            model_name='envanter',
            name='parca_tanimi',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Parça Tanımı'),
        ),
        migrations.AddField(
            model_name='envanter',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='envanter',
            name='saha_kodu',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Saha Kodu'),
        ),
        migrations.AddField(
            model_name='envanter',
            name='saha_no',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Saha No'),
        ),
        migrations.AddField(
            model_name='envanter',
            name='saha_tipi',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Saha Tipi'),
        ),
        migrations.AddField(
            model_name='envanter',
            name='sahaya_kurulum_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sahaya Kurulum Tarihi'),
        ),
        migrations.AddField(
            model_name='envanter',
            name='seri_no',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Seri No'),
        ),
        migrations.AddField(
            model_name='envanter',
            name='sirket',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Sirket'),
        ),
        migrations.AddField(
            model_name='envanter',
            name='stok_tipi_1',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Stok Tipi 1'),
        ),
        migrations.AddField(
            model_name='envanter',
            name='stok_tipi_2',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Stok Tipi 2'),
        ),
        migrations.AddField(
            model_name='envanter',
            name='stok_tipi_3',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Stok Tipi 3'),
        ),
        migrations.AddField(
            model_name='envanter',
            name='stok_tipi_4',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Stok Tipi 4'),
        ),
        migrations.AddField(
            model_name='envanter',
            name='stok_tipi_5',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Stok Tipi 5'),
        ),
        migrations.AddField(
            model_name='envanter',
            name='stok_tipi_6',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Stok Tipi 6'),
        ),
        migrations.AddField(
            model_name='envanter',
            name='stok_tipi_7',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Stok Tipi 7'),
        ),
        migrations.AddField(
            model_name='envanter',
            name='stok_tipi_8',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Stok Tipi 8'),
        ),
        migrations.AddField(
            model_name='envanter',
            name='teslim_alma_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Teslim Alma Tarihi'),
        ),
    ]
