# Generated by Django 3.2.3 on 2022-09-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0002_auto_20220914_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvanterTarihcesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_category', models.CharField(choices=[('sarf', 'sarf'), ('seri', 'seri')], default='sarf', max_length=64)),
                ('saha_kodu', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Saha Kodu')),
                ('sirket', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Sirket')),
                ('kullanici_adi', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Kullanici Adi')),
                ('olcum_birimi', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Olcum Birimi')),
                ('parca_kodu_tipi', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Parça Kodu Tipi')),
                ('birim_maliyet', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Birim Maliyet')),
                ('form_no', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Form No')),
                ('hedef_departman', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Hedef Departman')),
                ('islem_miktari', models.IntegerField(verbose_name='Islem Miktari')),
                ('islem_no', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Islem No')),
                ('islem_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Islem Tarihi')),
                ('islem_tipi', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Islem Tipi')),
                ('kalem_kategori', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Kalem Kategori')),
                ('kaynak_departman', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Kaynak Departman')),
                ('kaynak_organizasyon_kodu', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Kaynak Organizasyon Kodu')),
                ('kaynak_stok_adresi', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Kaynak Stok Adresi')),
                ('kaynak_stok_yeri', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Kaynak Stok Yeri')),
                ('kaynak_surec', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Kaynak Surec')),
                ('referans', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Referans')),
                ('transfer_organizasyon_kodu', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Transfer Organizasyon Kodu')),
                ('transfer_stok_adresi', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Transfer Stok Adresi')),
                ('transfer_stok_yeri', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Transfer Stok Yeri')),
                ('source_code', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Source Code')),
                ('parca_kodu', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Parça Kodu')),
                ('saha_no', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Saha No')),
                ('parca_tanimi', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Parça Tanımı')),
                ('seri_no', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Seri No')),
                ('ıs_emri', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Is Emri')),
                ('onent_kullanici', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='ONENT Kullanici')),
            ],
        ),
        migrations.DeleteModel(
            name='EnvanaterSayim',
        ),
    ]
