# Generated by Django 3.2.3 on 2022-09-16 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0055_delete_raporenvanter'),
        ('envanter', '0003_auto_20220914_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaporEnvanter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saha_no', models.CharField(default='', max_length=50, verbose_name='Saha No')),
                ('user', models.CharField(default='', max_length=50, verbose_name='Kullanıcı Adı')),
                ('seri_no', models.CharField(default='', max_length=5000, verbose_name='Seri No')),
                ('parca_kodu', models.CharField(default='', max_length=5000, verbose_name='Parça Kodu')),
                ('parca_tanimi', models.CharField(default='', max_length=5000, verbose_name='Parça Tanımı')),
                ('bolge', models.CharField(default='', max_length=5000, verbose_name='Bölge')),
                ('miktar', models.IntegerField(default=0, verbose_name='Miktar')),
                ('sayim_fark', models.IntegerField(default=0, verbose_name='Sayım Fark')),
                ('transfer_adet', models.IntegerField(default=0, verbose_name='Transfer Adet')),
                ('sonuc', models.CharField(default='', max_length=9999, verbose_name='Sonuç')),
                ('durum', models.CharField(default='', max_length=9999, verbose_name='Durum')),
                ('lokasyon', models.CharField(default='', max_length=9999, verbose_name='Lokasyon')),
                ('aciklama', models.CharField(default='', max_length=99999, verbose_name='Açıklama')),
                ('rapor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapor_envanterr', to='excel_app.rapor')),
            ],
            options={
                'verbose_name': 'Terminal Sayım Envanter',
                'verbose_name_plural': 'Terminal Sayım Envanter',
            },
        ),
    ]
