# Generated by Django 3.2.3 on 2022-09-16 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapor', '0002_rapor'),
        ('envanter', '0004_raporenvanter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raporenvanter',
            name='rapor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapor_envanter', to='rapor.rapor'),
        ),
    ]
