# Generated by Django 3.2.3 on 2022-09-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0005_alter_raporenvanter_rapor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ekipman_Hareketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_no', models.CharField(blank=True, max_length=500, null=True)),
                ('islem_tarihi', models.CharField(blank=True, max_length=500, null=True)),
                ('parca_kodu', models.CharField(blank=True, max_length=500, null=True)),
                ('parca_tanimi', models.CharField(blank=True, max_length=500, null=True)),
                ('islem_miktari', models.IntegerField(blank=True, null=True)),
                ('olcum_birimi', models.CharField(blank=True, max_length=500, null=True)),
                ('kaynak_yeri', models.CharField(blank=True, max_length=500, null=True)),
                ('islem_tipi', models.CharField(blank=True, max_length=500, null=True)),
                ('form_no', models.CharField(blank=True, max_length=500, null=True)),
                ('hedef_departman', models.CharField(blank=True, max_length=500, null=True)),
                ('hedef_lokasyon', models.CharField(blank=True, max_length=500, null=True)),
                ('kullanici_adi', models.CharField(blank=True, max_length=500, null=True)),
                ('ekipman_tipi', models.CharField(blank=True, max_length=500, null=True)),
                ('seri_no', models.CharField(blank=True, max_length=500, null=True)),
                ('maliyet', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SayimOncesiEnvanter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saha_no', models.CharField(default='', max_length=50, verbose_name='Saha No')),
                ('saha_kodu', models.CharField(default='', max_length=50, verbose_name='Saha Kod')),
                ('saha_tipi', models.CharField(default='', max_length=5000, verbose_name='Saha Tipi')),
                ('yer_tipi', models.CharField(default='', max_length=5000, verbose_name='Yer Tipi')),
                ('ekipman_seri_no', models.CharField(default='', max_length=5000, verbose_name='Ekipman Seri No')),
                ('ekipman_parca_kodu', models.CharField(default='', max_length=5000, verbose_name='Ekipman Parça Kodu')),
                ('parca_tanimi', models.CharField(default='', max_length=5000, verbose_name='Parça Tanımı')),
                ('kurulumu_tarihi', models.CharField(default='', max_length=5000, verbose_name='Tarih')),
                ('department_code', models.CharField(default='', max_length=5000, verbose_name='Department')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('ustekipman', models.CharField(default='', max_length=5000, verbose_name='Üst Ekipman')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Roma Envanter',
                'verbose_name_plural': 'Roma Envnterleri',
            },
        ),
    ]
