# Generated by Django 3.2.3 on 2022-09-18 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0006_ekipman_hareketi_sayimoncesienvanter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ekipman_Hareketi',
        ),
        migrations.DeleteModel(
            name='RaporEnvanter',
        ),
    ]
