# Generated by Django 3.2.3 on 2022-09-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0007_auto_20220918_2318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SayimOncesiEnvanter',
        ),
    ]
