# Generated by Django 3.2.3 on 2022-09-25 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0008_delete_sayimoncesienvanter'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewEnvanter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saha_no', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Saha No')),
                ('saha_kodu', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Saha Kodu')),
                ('kts_saha_no', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='KTS Saha No')),
                ('saha_tipi', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Saha Tipi')),
                ('ana_yer_tipi', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Ana Yer Tipi')),
                ('ekipman_no', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Ekipman No')),
                ('seri_no', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Seri No')),
                ('parca_kodu', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Parça Kodu')),
                ('parca_tanimi', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Parça Tanımı')),
                ('stok_tipi_1', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Stok Tipi 1')),
                ('stok_tipi_2', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Stok Tipi 2')),
                ('stok_tipi_3', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Stok Tipi 3')),
                ('stok_tipi_4', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Stok Tipi 4')),
                ('stok_tipi_5', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Stok Tipi 5')),
                ('stok_tipi_6', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Stok Tipi 6')),
                ('stok_tipi_7', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Stok Tipi 7')),
                ('stok_tipi_8', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Stok Tipi 8')),
                ('teslim_alma_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Teslim Alma Tarihi')),
                ('sahaya_kurulum_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Sahaya Kurulum Tarihi')),
                ('sirket', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Sirket')),
                ('organizasyon', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Organizasyon')),
                ('department', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Department')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
            ],
        ),
        migrations.AlterModelOptions(
            name='envanter',
            options={'verbose_name': 'Roma Envanter', 'verbose_name_plural': 'Roma Envnterleri'},
        ),
        migrations.RemoveField(
            model_name='envanter',
            name='ana_yer_tipi',
        ),
        migrations.RemoveField(
            model_name='envanter',
            name='department',
        ),
        migrations.RemoveField(
            model_name='envanter',
            name='ekipman_no',
        ),
        migrations.RemoveField(
            model_name='envanter',
            name='kts_saha_no',
        ),
        migrations.RemoveField(
            model_name='envanter',
            name='organizasyon',
        ),
        migrations.RemoveField(
            model_name='envanter',
            name='parca_kodu',
        ),
        migrations.RemoveField(
            model_name='envanter',
            name='sahaya_kurulum_tarihi',
        ),
        migrations.RemoveField(
            model_name='envanter',
            name='seri_no',
        ),
        migrations.RemoveField(
            model_name='envanter',
            name='sirket',
        ),
        migrations.RemoveField(
            model_name='envanter',
            name='stok_tipi_1',
        ),
        migrations.RemoveField(
            model_name='envanter',
            name='stok_tipi_2',
        ),
        migrations.RemoveField(
            model_name='envanter',
            name='stok_tipi_3',
        ),
        migrations.RemoveField(
            model_name='envanter',
            name='stok_tipi_4',
        ),
        migrations.RemoveField(
            model_name='envanter',
            name='stok_tipi_5',
        ),
        migrations.RemoveField(
            model_name='envanter',
            name='stok_tipi_6',
        ),
        migrations.RemoveField(
            model_name='envanter',
            name='stok_tipi_7',
        ),
        migrations.RemoveField(
            model_name='envanter',
            name='stok_tipi_8',
        ),
        migrations.RemoveField(
            model_name='envanter',
            name='teslim_alma_tarihi',
        ),
        migrations.AddField(
            model_name='envanter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='envanter',
            name='department_code',
            field=models.CharField(default='', max_length=5000, verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='envanter',
            name='ekipman_parca_kodu',
            field=models.CharField(default='', max_length=5000, verbose_name='Ekipman Parça Kodu'),
        ),
        migrations.AddField(
            model_name='envanter',
            name='ekipman_seri_no',
            field=models.CharField(default='', max_length=5000, verbose_name='Ekipman Seri No'),
        ),
        migrations.AddField(
            model_name='envanter',
            name='kurulumu_tarihi',
            field=models.CharField(default='', max_length=5000, verbose_name='Tarih'),
        ),
        migrations.AddField(
            model_name='envanter',
            name='ustekipman',
            field=models.CharField(default='', max_length=5000, verbose_name='Üst Ekipman'),
        ),
        migrations.AddField(
            model_name='envanter',
            name='yer_tipi',
            field=models.CharField(default='', max_length=5000, verbose_name='Yer Tipi'),
        ),
        migrations.AlterField(
            model_name='envanter',
            name='parca_tanimi',
            field=models.CharField(default='', max_length=5000, verbose_name='Parça Tanımı'),
        ),
        migrations.AlterField(
            model_name='envanter',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='envanter',
            name='saha_kodu',
            field=models.CharField(default='', max_length=50, verbose_name='Saha Kod'),
        ),
        migrations.AlterField(
            model_name='envanter',
            name='saha_no',
            field=models.CharField(default='', max_length=50, verbose_name='Saha No'),
        ),
        migrations.AlterField(
            model_name='envanter',
            name='saha_tipi',
            field=models.CharField(default='', max_length=5000, verbose_name='Saha Tipi'),
        ),
    ]
