# Generated by Django 3.2.3 on 2022-09-25 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envanter', '0009_auto_20220925_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='envanter',
            options={},
        ),
    ]
