# Generated by Django 3.2.3 on 2022-09-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ekipman_Hareketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_no', models.CharField(blank=True, max_length=500, null=True)),
                ('islem_tarihi', models.CharField(blank=True, max_length=500, null=True)),
                ('parca_kodu', models.CharField(blank=True, max_length=500, null=True)),
                ('parca_tanimi', models.CharField(blank=True, max_length=500, null=True)),
                ('islem_miktari', models.IntegerField(blank=True, null=True)),
                ('olcum_birimi', models.CharField(blank=True, max_length=500, null=True)),
                ('kaynak_yeri', models.CharField(blank=True, max_length=500, null=True)),
                ('islem_tipi', models.CharField(blank=True, max_length=500, null=True)),
                ('form_no', models.CharField(blank=True, max_length=500, null=True)),
                ('hedef_departman', models.CharField(blank=True, max_length=500, null=True)),
                ('hedef_lokasyon', models.CharField(blank=True, max_length=500, null=True)),
                ('kullanici_adi', models.CharField(blank=True, max_length=500, null=True)),
                ('ekipman_tipi', models.CharField(blank=True, max_length=500, null=True)),
                ('seri_no', models.CharField(blank=True, max_length=500, null=True)),
                ('maliyet', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
