# Generated by Django 3.2.3 on 2022-09-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eht', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ekipman_Hareketi',
            new_name='Envanter_Tarihcesi',
        ),
    ]
