# Generated by Django 3.2.3 on 2022-09-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departmanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=9999, verbose_name='Departman Kodu')),
                ('emails', models.TextField(help_text='Mailleri Her Satıra Bir Tane Gelecek Şekilde Yazın', verbose_name='Email Listesi')),
            ],
            options={
                'verbose_name': 'Bölge Mail Liste',
                'verbose_name_plural': 'Bölge Mail Listeleri',
            },
        ),
    ]
