# Generated by Django 3.2.3 on 2022-09-16 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departmanlar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rapor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saha_no', models.CharField(default='', max_length=9999, verbose_name='Saha No')),
                ('saha_kod', models.CharField(default='', max_length=9999, verbose_name='Saha Kodu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('onay', models.BooleanField(default=False, verbose_name="Rapor Onaylı'mı?")),
                ('hatali', models.BooleanField(default=False, verbose_name='Hatalı mı?')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rapor.rapor')),
                ('department_code', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Department_code', to='departmanlar.departmanlar')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raporlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kontrol-Bakım Raporu',
                'verbose_name_plural': 'Kontrol-Bakım Raporları',
            },
        ),
    ]
