# Generated by Django 3.2.3 on 2022-09-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapor', '0002_rapor'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSayimRapor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saha_no', models.CharField(default='', max_length=50, verbose_name='Saha No')),
                ('saha_kod', models.CharField(default='', max_length=50, verbose_name='Saha Kod')),
                ('ref_1', models.IntegerField(verbose_name='Referans-1')),
                ('ref_2', models.IntegerField(verbose_name='Referans-2')),
                ('ref_3', models.IntegerField(verbose_name='Referans-3')),
                ('ref_4', models.IntegerField(verbose_name='Referans-4')),
                ('ref_5', models.IntegerField(verbose_name='Referans-5')),
                ('ref_6', models.IntegerField(verbose_name='Referans-6')),
                ('ref_grup', models.CharField(default='', max_length=250, verbose_name='Ref Grup')),
                ('sonuc', models.CharField(default='', max_length=50, verbose_name='Sonuç')),
                ('kontrol', models.CharField(default='', max_length=250, verbose_name='Kontrol')),
                ('kategori', models.CharField(default='', max_length=50, verbose_name='Kategori')),
                ('sorgu_no', models.CharField(default='', max_length=50, verbose_name='Sorgu No')),
                ('department_code', models.CharField(default='', max_length=5000, verbose_name='Department')),
                ('aciklama', models.CharField(blank=True, default='', max_length=250, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Global Uyumsuzluk Rapor',
                'verbose_name_plural': 'Global Uyumsuzluk Raporları',
            },
        ),
        migrations.DeleteModel(
            name='GlobalRapor',
        ),
    ]
