# Generated by Django 3.2.3 on 2022-09-25 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapor', '0005_sayimsonrasienvanter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SayimSonrasiEnvanter',
            new_name='ScorSayım',
        ),
    ]
