# Generated by Django 3.2.3 on 2022-09-25 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapor', '0006_rename_sayimsonrasienvanter_scorsayım'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SayimRapor',
            new_name='ScorRapor',
        ),
    ]
