# Generated by Django 3.2.3 on 2022-09-25 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorgu', '0003_rename_raporreferanslari_sorgureferanslari'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SorguList',
            new_name='Sorgular',
        ),
    ]
