# Generated by Django 3.2.3 on 2022-09-25 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorgu', '0004_rename_sorgulist_sorgular'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sorgular',
            options={'verbose_name': 'Sorgu', 'verbose_name_plural': 'Sorgular'},
        ),
    ]
