# Generated by Django 3.2.3 on 2021-06-01 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departmanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=9999, verbose_name='Departman Kodu')),
                ('emails', models.TextField(help_text='Mailleri Her Satıra Bir Tane Gelecek Şekilde Yazın', verbose_name='Email Listesi')),
            ],
        ),
        migrations.CreateModel(
            name='HamVeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saha_no', models.CharField(default='', max_length=50, verbose_name='Saha No')),
                ('saha_kodu', models.CharField(default='', max_length=50, verbose_name='Saha Kod')),
                ('kts_saha_no', models.CharField(default='', max_length=50, verbose_name='KTS Saha No')),
                ('saha_tipi', models.CharField(default='', max_length=5000, verbose_name='Saha Tipi')),
                ('ana_yer_tipi', models.CharField(default='', max_length=5000, verbose_name='Ana Yer Tipi')),
                ('ekipman_no', models.CharField(default='', max_length=5000, verbose_name='Ekipman No')),
                ('ekipman_seri_no', models.CharField(default='', max_length=5000, verbose_name='Ekipman Seri No')),
                ('ekipman_parca_kodu', models.CharField(default='', max_length=5000, verbose_name='Ekipman Parça Kodu')),
                ('parca_tanimi', models.CharField(default='', max_length=5000, verbose_name='Parça Tanımı')),
                ('stok_tipi_1', models.CharField(default='', max_length=5000, verbose_name='Stok Tipi-1')),
                ('stok_tipi_2', models.CharField(default='', max_length=5000, verbose_name='Stok Tipi-2')),
                ('stok_tipi_3', models.CharField(default='', max_length=5000, verbose_name='Stok Tipi-3')),
                ('stok_tipi_4', models.CharField(default='', max_length=5000, verbose_name='Stok Tipi-4')),
                ('stok_tipi_5', models.CharField(default='', max_length=5000, verbose_name='Stok Tipi-5')),
                ('stok_tipi_6', models.CharField(default='', max_length=5000, verbose_name='Stok Tipi-6')),
                ('stok_tipi_7', models.CharField(default='', max_length=5000, verbose_name='Stok Tipi-7')),
                ('stok_tipi_8', models.CharField(default='', max_length=5000, verbose_name='Stok Tipi-8')),
                ('teslim_alma_tarihi', models.CharField(default='', max_length=5000, verbose_name='Teslim Alma Tarihi')),
                ('sahaya_kurulum_tarihi', models.CharField(default='', max_length=5000, verbose_name='Sahaya Kurulum Tarihi')),
                ('sirket', models.CharField(default='', max_length=5000, verbose_name='Şirket')),
                ('organization_code', models.CharField(default='', max_length=5000, verbose_name='Organization Code')),
                ('department_code', models.CharField(default='', max_length=5000, verbose_name='Department')),
                ('quantity', models.IntegerField(default='', verbose_name='Quantity')),
                ('ust_ekipman', models.CharField(default='', max_length=5000, verbose_name='Üst Ekipman')),
            ],
        ),
        migrations.CreateModel(
            name='Rapor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saha_no', models.CharField(default='', max_length=9999, verbose_name='Saha No')),
                ('saha_kod', models.CharField(default='', max_length=9999, verbose_name='Saha Kodu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('department_code', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='excel_app.departmanlar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RaporReferanslari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorgu_no', models.CharField(default='', max_length=5000, verbose_name='Sorgu No')),
                ('ref', models.CharField(default='', max_length=5000, verbose_name='Ref')),
                ('ekipman_parca_kodu', models.CharField(default='', max_length=5000, verbose_name='Ekipman Parça Kodu')),
                ('parca_tanimi', models.CharField(default='', max_length=5000, verbose_name='Parça Tanımı')),
                ('grup_tanimi', models.CharField(default='', max_length=5000, verbose_name='Grup Tanımı')),
                ('rapor_tanimi', models.CharField(default='', max_length=5000, verbose_name='Rapor Tanımı')),
                ('ref_grup', models.CharField(default='', max_length=5000, verbose_name='Ref Grup')),
                ('kategori', models.CharField(default='', max_length=5000, verbose_name='Kategori')),
                ('analiz_no', models.CharField(default='', max_length=5000, verbose_name='Analiz No')),
            ],
        ),
        migrations.CreateModel(
            name='SorguList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorgu_no', models.CharField(default='', max_length=5000, verbose_name='Sorgu No')),
                ('kontrol', models.CharField(default='', max_length=5000, verbose_name='Kontrol')),
                ('ref_grup', models.CharField(default='', max_length=5000, verbose_name='Ref Grup')),
                ('kategori', models.CharField(default='', max_length=5000, verbose_name='Kategori')),
                ('check', models.CharField(default='', max_length=5000, verbose_name='Check')),
            ],
        ),
        migrations.CreateModel(
            name='RaporGirdiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saha_no', models.CharField(default='', max_length=50, verbose_name='Saha No')),
                ('saha_kod', models.CharField(default='', max_length=50, verbose_name='Saha Kod')),
                ('ref_1', models.IntegerField(verbose_name='Referans-1')),
                ('ref_2', models.IntegerField(verbose_name='Referans-2')),
                ('ref_3', models.IntegerField(verbose_name='Referans-3')),
                ('ref_4', models.IntegerField(verbose_name='Referans-4')),
                ('ref_5', models.IntegerField(verbose_name='Referans-5')),
                ('ref_6', models.IntegerField(verbose_name='Referans-6')),
                ('ref_grup', models.CharField(default='', max_length=5000, verbose_name='Ref Grup')),
                ('sonuc', models.CharField(default='', max_length=50, verbose_name='Sonuç')),
                ('kontrol', models.CharField(default='', max_length=5000, verbose_name='Kontrol')),
                ('kategori', models.CharField(default='', max_length=50, verbose_name='Kategori')),
                ('sorgu_no', models.CharField(default='', max_length=50, verbose_name='Sorgu No')),
                ('aciklama', models.CharField(blank=True, default='', max_length=5000, verbose_name='Açıklama')),
                ('rapor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapor', to='excel_app.rapor')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saha_no', models.CharField(default='', max_length=50, verbose_name='Saha No')),
                ('saha_kod', models.CharField(default='', max_length=50, verbose_name='Saha Kod')),
                ('description', models.TextField(default='', max_length=9999999, verbose_name='Yaptığı İşlem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
