# Generated by Django 3.2.3 on 2021-06-01 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0002_alter_rapor_department_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raporgirdiler',
            name='rapor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='girdiler', to='excel_app.rapor'),
        ),
        migrations.CreateModel(
            name='SayimRaporGirdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saha_no', models.CharField(default='', max_length=9999, verbose_name='Saha No')),
                ('saha_kod', models.CharField(default='', max_length=9999, verbose_name='Saha Kodu')),
                ('seri', models.CharField(default='', max_length=9999, verbose_name='Seri')),
                ('ekipman_parca_kodu', models.CharField(default='', max_length=5000, verbose_name='Ekipman Parça Kodu')),
                ('quantity', models.IntegerField(default='', verbose_name='Quantity')),
                ('sayim', models.CharField(default='', max_length=50000, verbose_name='Sayım')),
                ('aciklama', models.CharField(default='', max_length=50000, verbose_name='Açıklama')),
                ('rapor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sayimGirdiler', to='excel_app.rapor')),
            ],
        ),
    ]
