# Generated by Django 3.2.3 on 2021-06-02 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0003_auto_20210601_0406'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RaporGirdiler',
            new_name='SayimOncesiRapor',
        ),
        migrations.RenameModel(
            old_name='SayimRaporGirdi',
            new_name='SayimSonrasiRapor',
        ),
    ]
