# Generated by Django 3.2.3 on 2021-06-02 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('excel_app', '0004_auto_20210602_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='SayimOncesiEnvanter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saha_no', models.CharField(default='', max_length=50, verbose_name='Saha No')),
                ('saha_kodu', models.CharField(default='', max_length=50, verbose_name='Saha Kod')),
                ('kts_saha_no', models.CharField(default='', max_length=50, verbose_name='KTS Saha No')),
                ('saha_tipi', models.CharField(default='', max_length=5000, verbose_name='Saha Tipi')),
                ('ana_yer_tipi', models.CharField(default='', max_length=5000, verbose_name='Ana Yer Tipi')),
                ('ekipman_no', models.CharField(default='', max_length=5000, verbose_name='Ekipman No')),
                ('ekipman_seri_no', models.CharField(default='', max_length=5000, verbose_name='Ekipman Seri No')),
                ('ekipman_parca_kodu', models.CharField(default='', max_length=5000, verbose_name='Ekipman Parça Kodu')),
                ('parca_tanimi', models.CharField(default='', max_length=5000, verbose_name='Parça Tanımı')),
                ('stok_tipi_1', models.CharField(default='', max_length=5000, verbose_name='Stok Tipi-1')),
                ('stok_tipi_2', models.CharField(default='', max_length=5000, verbose_name='Stok Tipi-2')),
                ('stok_tipi_3', models.CharField(default='', max_length=5000, verbose_name='Stok Tipi-3')),
                ('stok_tipi_4', models.CharField(default='', max_length=5000, verbose_name='Stok Tipi-4')),
                ('stok_tipi_5', models.CharField(default='', max_length=5000, verbose_name='Stok Tipi-5')),
                ('stok_tipi_6', models.CharField(default='', max_length=5000, verbose_name='Stok Tipi-6')),
                ('stok_tipi_7', models.CharField(default='', max_length=5000, verbose_name='Stok Tipi-7')),
                ('stok_tipi_8', models.CharField(default='', max_length=5000, verbose_name='Stok Tipi-8')),
                ('teslim_alma_tarihi', models.CharField(default='', max_length=5000, verbose_name='Teslim Alma Tarihi')),
                ('sahaya_kurulum_tarihi', models.CharField(default='', max_length=5000, verbose_name='Sahaya Kurulum Tarihi')),
                ('sirket', models.CharField(default='', max_length=5000, verbose_name='Şirket')),
                ('organization_code', models.CharField(default='', max_length=5000, verbose_name='Organization Code')),
                ('department_code', models.CharField(default='', max_length=5000, verbose_name='Department')),
                ('quantity', models.IntegerField(default='', verbose_name='Quantity')),
                ('ust_ekipman', models.CharField(default='', max_length=5000, verbose_name='Üst Ekipman')),
            ],
        ),
        migrations.DeleteModel(
            name='HamVeri',
        ),
        migrations.AlterField(
            model_name='rapor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sayimoncesienvanter',
            name='rapor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excel_app.rapor'),
        ),
    ]
