# Generated by Django 3.2.3 on 2021-06-02 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0005_auto_20210602_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sayimoncesienvanter',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='sayimoncesienvanter',
            name='rapor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='excel_app.rapor'),
        ),
    ]
