# Generated by Django 3.2.3 on 2021-06-02 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0007_alter_sayimoncesienvanter_rapor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sayimoncesienvanter',
            name='rapor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='excel_app.rapor'),
        ),
    ]
