# Generated by Django 3.2.3 on 2021-06-02 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0009_sayimsonrasienvanter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sayimoncesirapor',
            old_name='rapor_id',
            new_name='rapor',
        ),
    ]
