# Generated by Django 3.2.3 on 2021-06-02 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0010_rename_rapor_id_sayimoncesirapor_rapor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sayimsonrasienvanter',
            name='rapor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sayim_sonrasi_envanter', to='excel_app.rapor'),
        ),
    ]
