# Generated by Django 3.2.3 on 2021-06-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0011_alter_sayimsonrasienvanter_rapor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SayimSonrasiRapor',
        ),
    ]
