# Generated by Django 3.2.3 on 2021-06-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0013_auto_20210602_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapor',
            name='onay',
            field=models.BooleanField(default=False, verbose_name="Rapor Onaylı'mı?"),
        ),
    ]
