# Generated by Django 3.2.3 on 2021-06-03 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0014_rapor_onay'),
    ]

    operations = [
        migrations.AddField(
            model_name='sayimrapor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi'),
            preserve_default=False,
        ),
    ]
