# Generated by Django 3.2.3 on 2021-06-04 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0015_sayimrapor_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapor',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='excel_app.rapor'),
        ),
    ]
