# Generated by Django 3.2.3 on 2021-06-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0020_raporenvanter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raporenvanter',
            name='aciklama',
        ),
        migrations.RemoveField(
            model_name='raporenvanter',
            name='department_code',
        ),
        migrations.RemoveField(
            model_name='raporenvanter',
            name='ekipman_parca_kodu',
        ),
        migrations.RemoveField(
            model_name='raporenvanter',
            name='ekipman_seri_no',
        ),
        migrations.RemoveField(
            model_name='raporenvanter',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='raporenvanter',
            name='saha_kodu',
        ),
        migrations.AddField(
            model_name='raporenvanter',
            name='bolge',
            field=models.CharField(default='', max_length=5000, verbose_name='Bölge'),
        ),
        migrations.AddField(
            model_name='raporenvanter',
            name='durum',
            field=models.CharField(default='', max_length=9999, verbose_name='Durum'),
        ),
        migrations.AddField(
            model_name='raporenvanter',
            name='lokasyon',
            field=models.CharField(default='', max_length=9999, verbose_name='Lokasyon'),
        ),
        migrations.AddField(
            model_name='raporenvanter',
            name='miktar',
            field=models.IntegerField(default=0, verbose_name='Miktar'),
        ),
        migrations.AddField(
            model_name='raporenvanter',
            name='parca_kodu',
            field=models.CharField(default='', max_length=5000, verbose_name='Parça Kodu'),
        ),
        migrations.AddField(
            model_name='raporenvanter',
            name='sayim_fark',
            field=models.IntegerField(default=0, verbose_name='Sayım Fark'),
        ),
        migrations.AddField(
            model_name='raporenvanter',
            name='seri_no',
            field=models.CharField(default='', max_length=5000, verbose_name='Seri No'),
        ),
        migrations.AddField(
            model_name='raporenvanter',
            name='sonuc',
            field=models.CharField(default='', max_length=9999, verbose_name='Sonuç'),
        ),
        migrations.AddField(
            model_name='raporenvanter',
            name='transfer_adet',
            field=models.IntegerField(default=0, verbose_name='Transfer Adet'),
        ),
        migrations.AddField(
            model_name='raporenvanter',
            name='user',
            field=models.CharField(default='', max_length=50, verbose_name='Kullanıcı Adı'),
        ),
    ]
