# Generated by Django 3.2.3 on 2021-06-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0021_auto_20210609_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='raporenvanter',
            name='aciklama',
            field=models.CharField(default='', max_length=99999, verbose_name='Açıklama'),
        ),
    ]
