# Generated by Django 3.2.3 on 2021-06-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0023_userprofile_bakimci'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='denetci',
            field=models.BooleanField(default=False, verbose_name='Denetçi'),
        ),
    ]
