# Generated by Django 3.2.3 on 2021-07-01 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0025_auto_20210630_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sayimoncesienvanter',
            name='ana_yer_tipi',
        ),
        migrations.RemoveField(
            model_name='sayimoncesienvanter',
            name='ekipman_no',
        ),
        migrations.RemoveField(
            model_name='sayimoncesienvanter',
            name='kts_saha_no',
        ),
        migrations.RemoveField(
            model_name='sayimoncesienvanter',
            name='organization_code',
        ),
        migrations.RemoveField(
            model_name='sayimoncesienvanter',
            name='sahaya_kurulum_tarihi',
        ),
        migrations.RemoveField(
            model_name='sayimoncesienvanter',
            name='sirket',
        ),
        migrations.RemoveField(
            model_name='sayimoncesienvanter',
            name='stok_tipi_1',
        ),
        migrations.RemoveField(
            model_name='sayimoncesienvanter',
            name='stok_tipi_2',
        ),
        migrations.RemoveField(
            model_name='sayimoncesienvanter',
            name='stok_tipi_3',
        ),
        migrations.RemoveField(
            model_name='sayimoncesienvanter',
            name='stok_tipi_4',
        ),
        migrations.RemoveField(
            model_name='sayimoncesienvanter',
            name='stok_tipi_5',
        ),
        migrations.RemoveField(
            model_name='sayimoncesienvanter',
            name='stok_tipi_6',
        ),
        migrations.RemoveField(
            model_name='sayimoncesienvanter',
            name='stok_tipi_7',
        ),
        migrations.RemoveField(
            model_name='sayimoncesienvanter',
            name='stok_tipi_8',
        ),
        migrations.RemoveField(
            model_name='sayimoncesienvanter',
            name='teslim_alma_tarihi',
        ),
        migrations.RemoveField(
            model_name='sayimoncesienvanter',
            name='ust_ekipman',
        ),
    ]
