# Generated by Django 3.2.3 on 2021-07-01 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0026_auto_20210701_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sayimoncesienvanter',
            name='rapor',
        ),
    ]
