# Generated by Django 3.2.3 on 2021-07-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0027_remove_sayimoncesienvanter_rapor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcakodu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parca_tip', models.CharField(default='', max_length=10, verbose_name='Tip')),
                ('parca_birim', models.CharField(default='', max_length=10, verbose_name='Birim')),
                ('ekipman_parca_kodu', models.CharField(default='', max_length=5000, verbose_name='Ekipman Parça Kodu')),
                ('parca_tanimi', models.CharField(default='', max_length=5000, verbose_name='Parça Tanımı')),
                ('grup_tanimi', models.CharField(default='', max_length=5000, verbose_name='Grup Tanımı')),
                ('ekip_tanimi', models.CharField(default='', max_length=5000, verbose_name='Ekip Tanımı')),
                ('ekip_aciklama', models.CharField(default='', max_length=5000, verbose_name='Ekip Açıklama')),
            ],
            options={
                'verbose_name': 'Parça Kodu',
                'verbose_name_plural': 'Parça Kodu Listesi',
            },
        ),
        migrations.AlterModelOptions(
            name='raporenvanter',
            options={'verbose_name': 'Terminal Sayım Envanter', 'verbose_name_plural': 'Terminal Sayım Envanter'},
        ),
        migrations.AlterModelOptions(
            name='sayimoncesienvanter',
            options={'verbose_name': 'Roma Envanter', 'verbose_name_plural': 'Roma Envnterleri'},
        ),
    ]
