# Generated by Django 3.2.3 on 2022-03-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0034_auto_20220217_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='sayimoncesienvanter',
            name='kurulumu_tarihi',
            field=models.CharField(default='', max_length=5000, verbose_name='Tarih'),
        ),
        migrations.AddField(
            model_name='sayimoncesienvanter',
            name='yer_tipi',
            field=models.CharField(default='', max_length=5000, verbose_name='Yer Tipi'),
        ),
    ]
