# Generated by Django 3.2.3 on 2022-03-05 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('excel_app', '0036_sayimoncesienvanter_ustekipman'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='aksiyon',
            field=models.CharField(default='', max_length=50, verbose_name='Aksiyon'),
        ),
        migrations.CreateModel(
            name='Detay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aksiyon', models.CharField(default='', max_length=50, verbose_name='Aksiyon')),
                ('saha_no', models.CharField(default='', max_length=50, verbose_name='Saha No')),
                ('saha_kod', models.CharField(default='', max_length=50, verbose_name='Saha Kod')),
                ('description', models.TextField(default='', max_length=9999999, verbose_name='Yaptığı İşlem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
