# Generated by Django 3.2.3 on 2022-03-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0037_auto_20220305_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='master',
            field=models.BooleanField(default=False, verbose_name='Master'),
        ),
    ]
