# Generated by Django 3.2.3 on 2022-03-09 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0038_userprofile_master'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcakodu',
            old_name='parca_tip',
            new_name='ekipman_tipi',
        ),
        migrations.RenameField(
            model_name='parcakodu',
            old_name='parca_birim',
            new_name='olcum_birimi',
        ),
        migrations.RenameField(
            model_name='parcakodu',
            old_name='ekipman_parca_kodu',
            new_name='parca_kodu',
        ),
    ]
