# Generated by Django 3.2.3 on 2022-03-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0039_auto_20220309_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='SahaListesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saha_kodu', models.CharField(blank=True, max_length=400, null=True)),
                ('saha_no', models.CharField(blank=True, max_length=400, null=True)),
                ('department_code', models.CharField(blank=True, max_length=400, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('yer_tipi', models.CharField(blank=True, max_length=400, null=True)),
                ('saha_tipi', models.CharField(blank=True, max_length=400, null=True)),
                ('status', models.CharField(choices=[('A', 'Aktif'), ('P', 'Pasif')], default='A', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryExcelFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='sheets/')),
            ],
        ),
    ]
