# Generated by Django 3.2.3 on 2022-03-20 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0042_auto_20220320_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekipman_hareketi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Oluşturulma Tarihi'),
            preserve_default=False,
        ),
    ]
