# Generated by Django 3.2.3 on 2022-03-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0046_parcakodu_muadil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ekipman_hareketi',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='ekipman_hareketi',
            name='islem_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
