# Generated by Django 3.2.3 on 2022-03-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0047_auto_20220328_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekipman_hareketi',
            name='islem_tarihi',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
