# Generated by Django 3.2.3 on 2022-04-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0050_alter_ekipman_hareketi_islem_tarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ekipman_hareketi',
            name='islem_tarihi',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
