# Generated by Django 3.2.3 on 2022-09-11 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0051_alter_ekipman_hareketi_islem_tarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapor',
            name='department_code',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Department_code', to='excel_app.departmanlar'),
        ),
    ]
