# Generated by Django 3.2.3 on 2022-09-16 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0052_alter_rapor_department_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parcakodu',
        ),
    ]
