# Generated by Django 3.2.3 on 2022-09-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0054_auto_20220916_1332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RaporEnvanter',
        ),
    ]
