# Generated by Django 3.2.3 on 2022-09-16 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0055_delete_raporenvanter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapor',
            name='child',
        ),
        migrations.RemoveField(
            model_name='rapor',
            name='department_code',
        ),
        migrations.RemoveField(
            model_name='rapor',
            name='user',
        ),
    ]
