# Generated by Django 3.2.3 on 2022-09-17 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0057_auto_20220916_1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SorguList',
        ),
    ]
