# Generated by Django 3.2.3 on 2022-09-17 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0058_delete_sorgulist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RaporReferanslari',
        ),
        migrations.DeleteModel(
            name='SahaListesi',
        ),
    ]
