# Generated by Django 3.2.3 on 2022-09-17 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0059_auto_20220918_0121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalSayimRapor',
        ),
    ]
