# Generated by Django 3.2.3 on 2022-09-17 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel_app', '0061_auto_20220918_0150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ekipman_Hareketi',
        ),
        migrations.DeleteModel(
            name='SayimOncesiEnvanter',
        ),
    ]
