# Generated by Django 3.2.3 on 2022-09-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SahaListesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saha_kodu', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Saha Kodu')),
                ('saha_no', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Saha No')),
                ('department', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Department')),
                ('durum', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Durum')),
                ('saha_tipi', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Saha Tipi')),
                ('ana_yer_tipi', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='Ana Yer Tipi')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='created_at')),
                ('il', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='İl')),
                ('update_at', models.DateTimeField(blank=True, null=True, verbose_name='update_at')),
                ('ilce', models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name='İlçe')),
            ],
        ),
    ]
