# Generated by Django 3.2.3 on 2022-09-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahalistesi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sahalistesi',
            name='ana_yer_tipi',
        ),
        migrations.RemoveField(
            model_name='sahalistesi',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sahalistesi',
            name='department',
        ),
        migrations.RemoveField(
            model_name='sahalistesi',
            name='durum',
        ),
        migrations.RemoveField(
            model_name='sahalistesi',
            name='il',
        ),
        migrations.RemoveField(
            model_name='sahalistesi',
            name='ilce',
        ),
        migrations.RemoveField(
            model_name='sahalistesi',
            name='update_at',
        ),
        migrations.AddField(
            model_name='sahalistesi',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sahalistesi',
            name='department_code',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='sahalistesi',
            name='status',
            field=models.CharField(choices=[('A', 'Aktif'), ('P', 'Pasif')], default='A', max_length=2),
        ),
        migrations.AddField(
            model_name='sahalistesi',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sahalistesi',
            name='yer_tipi',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='sahalistesi',
            name='saha_kodu',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='sahalistesi',
            name='saha_no',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='sahalistesi',
            name='saha_tipi',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
